name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build-ps2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - docker: ps2dev/ps2dev:latest
           platform: "ps2"
           dump: ee-objdump
           strip: ee-strip
         - docker: ps2dev/ps2dev:experimental
           platform: "ps2_experimental"
           dump: mips64r5900el-ps2-elf-objdump
           strip: mips64r5900el-ps2-elf-strip
    container: ${{ matrix.docker }}
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git

    - uses: actions/checkout@v2

    - name: Compile test core
      run: |
        cd HelloWorld && make clean && make
    
    - name: Print sections
      run: |
        cd HelloWorld && ${{ matrix.dump }} -x hello.elf

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: helloWorld_${{ matrix.platform }}
        path: HelloWorld/hello.elf
    
    - name: Strip binary
      run: |
        cd HelloWorld && ${{ matrix.strip }} -s hello.elf

    - name: Print Stripped sections
      run: |
        cd HelloWorld && ${{ matrix.dump }} -x hello.elf

    - name: Upload stripped artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: helloWorld_${{ matrix.platform }}_stripped
        path: HelloWorld/hello.elf